/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransporteRouteImport } from './routes/transporte'
import { Route as TomosRouteImport } from './routes/tomos'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as RutasRouteImport } from './routes/rutas'
import { Route as RealitoRouteImport } from './routes/realito'
import { Route as RdmQuestRouteImport } from './routes/rdm-quest'
import { Route as NodoCeroRouteImport } from './routes/nodo-cero'
import { Route as MusicaRouteImport } from './routes/musica'
import { Route as MembresiasRouteImport } from './routes/membresias'
import { Route as MapaVivoRouteImport } from './routes/mapa-vivo'
import { Route as LtosRouteImport } from './routes/ltos'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GastronomiaRouteImport } from './routes/gastronomia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ForosRouteImport } from './routes/foros'
import { Route as FederacionRouteImport } from './routes/federacion'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DichosRouteImport } from './routes/dichos'
import { Route as CulturaRouteImport } from './routes/cultura'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as ComerciosRouteImport } from './routes/comercios'
import { Route as AventuraRouteImport } from './routes/aventura'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIsabellaChatRouteImport } from './routes/api/isabella-chat'
import { Route as AuthenticatedIsabellaRouteImport } from './routes/_authenticated/isabella'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const TransporteRoute = TransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TomosRoute = TomosRouteImport.update({
  id: '/tomos',
  path: '/tomos',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const RutasRoute = RutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => rootRouteImport,
} as any)
const RealitoRoute = RealitoRouteImport.update({
  id: '/realito',
  path: '/realito',
  getParentRoute: () => rootRouteImport,
} as any)
const RdmQuestRoute = RdmQuestRouteImport.update({
  id: '/rdm-quest',
  path: '/rdm-quest',
  getParentRoute: () => rootRouteImport,
} as any)
const NodoCeroRoute = NodoCeroRouteImport.update({
  id: '/nodo-cero',
  path: '/nodo-cero',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicaRoute = MusicaRouteImport.update({
  id: '/musica',
  path: '/musica',
  getParentRoute: () => rootRouteImport,
} as any)
const MembresiasRoute = MembresiasRouteImport.update({
  id: '/membresias',
  path: '/membresias',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaVivoRoute = MapaVivoRouteImport.update({
  id: '/mapa-vivo',
  path: '/mapa-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const LtosRoute = LtosRouteImport.update({
  id: '/ltos',
  path: '/ltos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GastronomiaRoute = GastronomiaRouteImport.update({
  id: '/gastronomia',
  path: '/gastronomia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ForosRoute = ForosRouteImport.update({
  id: '/foros',
  path: '/foros',
  getParentRoute: () => rootRouteImport,
} as any)
const FederacionRoute = FederacionRouteImport.update({
  id: '/federacion',
  path: '/federacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DichosRoute = DichosRouteImport.update({
  id: '/dichos',
  path: '/dichos',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturaRoute = CulturaRouteImport.update({
  id: '/cultura',
  path: '/cultura',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ComerciosRoute = ComerciosRouteImport.update({
  id: '/comercios',
  path: '/comercios',
  getParentRoute: () => rootRouteImport,
} as any)
const AventuraRoute = AventuraRouteImport.update({
  id: '/aventura',
  path: '/aventura',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIsabellaChatRoute = ApiIsabellaChatRouteImport.update({
  id: '/api/isabella-chat',
  path: '/api/isabella-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIsabellaRoute = AuthenticatedIsabellaRouteImport.update({
  id: '/isabella',
  path: '/isabella',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/aventura': typeof AventuraRoute
  '/comercios': typeof ComerciosRoute
  '/comunidad': typeof ComunidadRoute
  '/cultura': typeof CulturaRoute
  '/dichos': typeof DichosRoute
  '/eventos': typeof EventosRoute
  '/federacion': typeof FederacionRoute
  '/foros': typeof ForosRoute
  '/galeria': typeof GaleriaRoute
  '/gastronomia': typeof GastronomiaRoute
  '/historia': typeof HistoriaRoute
  '/ltos': typeof LtosRoute
  '/mapa-vivo': typeof MapaVivoRoute
  '/membresias': typeof MembresiasRoute
  '/musica': typeof MusicaRoute
  '/nodo-cero': typeof NodoCeroRoute
  '/rdm-quest': typeof RdmQuestRoute
  '/realito': typeof RealitoRoute
  '/rutas': typeof RutasRoute
  '/tienda': typeof TiendaRoute
  '/tomos': typeof TomosRoute
  '/transporte': typeof TransporteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/isabella': typeof AuthenticatedIsabellaRoute
  '/api/isabella-chat': typeof ApiIsabellaChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/aventura': typeof AventuraRoute
  '/comercios': typeof ComerciosRoute
  '/comunidad': typeof ComunidadRoute
  '/cultura': typeof CulturaRoute
  '/dichos': typeof DichosRoute
  '/eventos': typeof EventosRoute
  '/federacion': typeof FederacionRoute
  '/foros': typeof ForosRoute
  '/galeria': typeof GaleriaRoute
  '/gastronomia': typeof GastronomiaRoute
  '/historia': typeof HistoriaRoute
  '/ltos': typeof LtosRoute
  '/mapa-vivo': typeof MapaVivoRoute
  '/membresias': typeof MembresiasRoute
  '/musica': typeof MusicaRoute
  '/nodo-cero': typeof NodoCeroRoute
  '/rdm-quest': typeof RdmQuestRoute
  '/realito': typeof RealitoRoute
  '/rutas': typeof RutasRoute
  '/tienda': typeof TiendaRoute
  '/tomos': typeof TomosRoute
  '/transporte': typeof TransporteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/isabella': typeof AuthenticatedIsabellaRoute
  '/api/isabella-chat': typeof ApiIsabellaChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/aventura': typeof AventuraRoute
  '/comercios': typeof ComerciosRoute
  '/comunidad': typeof ComunidadRoute
  '/cultura': typeof CulturaRoute
  '/dichos': typeof DichosRoute
  '/eventos': typeof EventosRoute
  '/federacion': typeof FederacionRoute
  '/foros': typeof ForosRoute
  '/galeria': typeof GaleriaRoute
  '/gastronomia': typeof GastronomiaRoute
  '/historia': typeof HistoriaRoute
  '/ltos': typeof LtosRoute
  '/mapa-vivo': typeof MapaVivoRoute
  '/membresias': typeof MembresiasRoute
  '/musica': typeof MusicaRoute
  '/nodo-cero': typeof NodoCeroRoute
  '/rdm-quest': typeof RdmQuestRoute
  '/realito': typeof RealitoRoute
  '/rutas': typeof RutasRoute
  '/tienda': typeof TiendaRoute
  '/tomos': typeof TomosRoute
  '/transporte': typeof TransporteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/isabella': typeof AuthenticatedIsabellaRoute
  '/api/isabella-chat': typeof ApiIsabellaChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/auth'
    | '/aventura'
    | '/comercios'
    | '/comunidad'
    | '/cultura'
    | '/dichos'
    | '/eventos'
    | '/federacion'
    | '/foros'
    | '/galeria'
    | '/gastronomia'
    | '/historia'
    | '/ltos'
    | '/mapa-vivo'
    | '/membresias'
    | '/musica'
    | '/nodo-cero'
    | '/rdm-quest'
    | '/realito'
    | '/rutas'
    | '/tienda'
    | '/tomos'
    | '/transporte'
    | '/dashboard'
    | '/isabella'
    | '/api/isabella-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/auth'
    | '/aventura'
    | '/comercios'
    | '/comunidad'
    | '/cultura'
    | '/dichos'
    | '/eventos'
    | '/federacion'
    | '/foros'
    | '/galeria'
    | '/gastronomia'
    | '/historia'
    | '/ltos'
    | '/mapa-vivo'
    | '/membresias'
    | '/musica'
    | '/nodo-cero'
    | '/rdm-quest'
    | '/realito'
    | '/rutas'
    | '/tienda'
    | '/tomos'
    | '/transporte'
    | '/dashboard'
    | '/isabella'
    | '/api/isabella-chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/atlas'
    | '/auth'
    | '/aventura'
    | '/comercios'
    | '/comunidad'
    | '/cultura'
    | '/dichos'
    | '/eventos'
    | '/federacion'
    | '/foros'
    | '/galeria'
    | '/gastronomia'
    | '/historia'
    | '/ltos'
    | '/mapa-vivo'
    | '/membresias'
    | '/musica'
    | '/nodo-cero'
    | '/rdm-quest'
    | '/realito'
    | '/rutas'
    | '/tienda'
    | '/tomos'
    | '/transporte'
    | '/_authenticated/dashboard'
    | '/_authenticated/isabella'
    | '/api/isabella-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AtlasRoute: typeof AtlasRoute
  AuthRoute: typeof AuthRoute
  AventuraRoute: typeof AventuraRoute
  ComerciosRoute: typeof ComerciosRoute
  ComunidadRoute: typeof ComunidadRoute
  CulturaRoute: typeof CulturaRoute
  DichosRoute: typeof DichosRoute
  EventosRoute: typeof EventosRoute
  FederacionRoute: typeof FederacionRoute
  ForosRoute: typeof ForosRoute
  GaleriaRoute: typeof GaleriaRoute
  GastronomiaRoute: typeof GastronomiaRoute
  HistoriaRoute: typeof HistoriaRoute
  LtosRoute: typeof LtosRoute
  MapaVivoRoute: typeof MapaVivoRoute
  MembresiasRoute: typeof MembresiasRoute
  MusicaRoute: typeof MusicaRoute
  NodoCeroRoute: typeof NodoCeroRoute
  RdmQuestRoute: typeof RdmQuestRoute
  RealitoRoute: typeof RealitoRoute
  RutasRoute: typeof RutasRoute
  TiendaRoute: typeof TiendaRoute
  TomosRoute: typeof TomosRoute
  TransporteRoute: typeof TransporteRoute
  ApiIsabellaChatRoute: typeof ApiIsabellaChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transporte': {
      id: '/transporte'
      path: '/transporte'
      fullPath: '/transporte'
      preLoaderRoute: typeof TransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tomos': {
      id: '/tomos'
      path: '/tomos'
      fullPath: '/tomos'
      preLoaderRoute: typeof TomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutas': {
      id: '/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof RutasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realito': {
      id: '/realito'
      path: '/realito'
      fullPath: '/realito'
      preLoaderRoute: typeof RealitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdm-quest': {
      id: '/rdm-quest'
      path: '/rdm-quest'
      fullPath: '/rdm-quest'
      preLoaderRoute: typeof RdmQuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodo-cero': {
      id: '/nodo-cero'
      path: '/nodo-cero'
      fullPath: '/nodo-cero'
      preLoaderRoute: typeof NodoCeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musica': {
      id: '/musica'
      path: '/musica'
      fullPath: '/musica'
      preLoaderRoute: typeof MusicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membresias': {
      id: '/membresias'
      path: '/membresias'
      fullPath: '/membresias'
      preLoaderRoute: typeof MembresiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-vivo': {
      id: '/mapa-vivo'
      path: '/mapa-vivo'
      fullPath: '/mapa-vivo'
      preLoaderRoute: typeof MapaVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ltos': {
      id: '/ltos'
      path: '/ltos'
      fullPath: '/ltos'
      preLoaderRoute: typeof LtosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastronomia': {
      id: '/gastronomia'
      path: '/gastronomia'
      fullPath: '/gastronomia'
      preLoaderRoute: typeof GastronomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foros': {
      id: '/foros'
      path: '/foros'
      fullPath: '/foros'
      preLoaderRoute: typeof ForosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federacion': {
      id: '/federacion'
      path: '/federacion'
      fullPath: '/federacion'
      preLoaderRoute: typeof FederacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dichos': {
      id: '/dichos'
      path: '/dichos'
      fullPath: '/dichos'
      preLoaderRoute: typeof DichosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultura': {
      id: '/cultura'
      path: '/cultura'
      fullPath: '/cultura'
      preLoaderRoute: typeof CulturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercios': {
      id: '/comercios'
      path: '/comercios'
      fullPath: '/comercios'
      preLoaderRoute: typeof ComerciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aventura': {
      id: '/aventura'
      path: '/aventura'
      fullPath: '/aventura'
      preLoaderRoute: typeof AventuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/isabella-chat': {
      id: '/api/isabella-chat'
      path: '/api/isabella-chat'
      fullPath: '/api/isabella-chat'
      preLoaderRoute: typeof ApiIsabellaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/isabella': {
      id: '/_authenticated/isabella'
      path: '/isabella'
      fullPath: '/isabella'
      preLoaderRoute: typeof AuthenticatedIsabellaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIsabellaRoute: typeof AuthenticatedIsabellaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIsabellaRoute: AuthenticatedIsabellaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AtlasRoute: AtlasRoute,
  AuthRoute: AuthRoute,
  AventuraRoute: AventuraRoute,
  ComerciosRoute: ComerciosRoute,
  ComunidadRoute: ComunidadRoute,
  CulturaRoute: CulturaRoute,
  DichosRoute: DichosRoute,
  EventosRoute: EventosRoute,
  FederacionRoute: FederacionRoute,
  ForosRoute: ForosRoute,
  GaleriaRoute: GaleriaRoute,
  GastronomiaRoute: GastronomiaRoute,
  HistoriaRoute: HistoriaRoute,
  LtosRoute: LtosRoute,
  MapaVivoRoute: MapaVivoRoute,
  MembresiasRoute: MembresiasRoute,
  MusicaRoute: MusicaRoute,
  NodoCeroRoute: NodoCeroRoute,
  RdmQuestRoute: RdmQuestRoute,
  RealitoRoute: RealitoRoute,
  RutasRoute: RutasRoute,
  TiendaRoute: TiendaRoute,
  TomosRoute: TomosRoute,
  TransporteRoute: TransporteRoute,
  ApiIsabellaChatRoute: ApiIsabellaChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
